index:
    path: /
    controller: App\Controller\IndexController::indexAction
#------------------------------------------------------------------------------------------------
registration:
    path: /registration
    controller: App\Controller\RegistrationController::createNewUserAction
#------------------------------------------------------------------------------------------------

viewMenu:
    path: /menu
    controller: App\Controller\ViewMenuController:viewMenuAction

#------------------------------------------------------------------------------------------------
createVillage:
    path: /createnewvillage
    controller: App\Controller\CreateNewVillageController:createNewVillageAction


myProfilVillage:
    path: /village/{id}
    controller: App\Controller\ViewVillageController:viewVillageAction


#------------------------------------------------------------------------------------------------
logout:
    path: /logout