index:
    path: /
    controller: App\Controller\IndexController::indexAction
#------------------------------------------------------------------------------------------------
registration:
    path: /registration
    controller: App\Controller\RegistrationController::createNewUserAction
#------------------------------------------------------------------------------------------------

viewMenu:
    path: /menu
    controller: App\Controller\ViewMenuController:viewMenuAction

#------------------------------------------------------------------------------------------------
createVillage:
    path: /createnewvillage
    controller: App\Controller\CreateNewVillageController:createNewVillageAction


myProfilVillage:
    path: /village/{id}
    controller: App\Controller\ViewVillageController:viewVillageAction

editProfilVillage:
    path: /editvilage
    controller: App\Controller\EditVillageController:editVillageAction


#------------------------------------------------------------------------------------------------
logout:
    path: /logout

checkStatus:
    path: /checkstatus
    controller : App\Controller\CheckStatusMissionController:checkStatusAction

#------------------------------------------------------------------------------------------------
#FOOD:
viewFood:
    path: /viewfood
    controller: App\Controller\ViewFoodController:getFoodAction

getFood:
    path: /getfood
    controller: App\Controller\GetFoodController:getFoodAction

addedLevelFood:
    path: /addedlevelfood
    controller: App\Controller\AddLevelFoodController:addLevelFoodAction


#------------------------------------------------------------------------------------------------
#Stone:
viewStone:
    path: /viewstone
    controller: App\Controller\ViewStoneController:getStoneAction

getStone:
    path: /getstone
    controller: App\Controller\GetStoneController:getStoneAction

addedLevelStone:
    path: /addedlevelstone
    controller: App\Controller\AddLevelStoneController:addLevelStoneAction


#------------------------------------------------------------------------------------------------
#Carbon:
viewCarbon:
    path: /viewcarbon
    controller: App\Controller\ViewCarbonController:getCarbonAction

getCarbon:
    path: /getcarbon
    controller: App\Controller\GetCarbonController:getCarbonAction

addedLevelCarbon:
    path: /addedlevelcarbon
    controller: App\Controller\AddLevelCarbonController:addLevelCarbonAction


#------------------------------------------------------------------------------------------------
##Wood:
viewWood:
    path: /viewwood
    controller: App\Controller\ViewWoodController:getWoodAction

getWood:
    path: /getwood
    controller: App\Controller\GetWoodController:getWoodAction

addedLevelWood:
    path: /addedlevelwood
    controller: App\Controller\AddLevelWoodController:addLevelWoodAction


##------------------------------------------------------------------------------------------------
#Gold:
viewGold:
    path: /viewgold
    controller: App\Controller\ViewGoldController:getGoldAction

getGold:
    path: /getgold
    controller: App\Controller\GetGoldController:getGoldAction

addedLevelGold:
    path: /addedlevelgold
    controller: App\Controller\AddLevelGoldController:addLevelGoldAction

##------------------------------------------------------------------------------------------------
#ExpandVillage:
expandVillage:
    path: /expandvillage
    controller: App\Controller\ExpandVillageController:expandVillageAction

addHouse:
    path: /addhouse
    controller: App\Controller\AddHouseController:addHouseAction

addHouseFinish:
    path: /addhouse/{population}
    controller: App\Controller\AddHouseController:addHouseFinishAction

addCastle:
    path: /addcastle
    controller: App\Controller\AddCastleController:addCastleAction

addCastleFinish:
    path: /addcastle/{population}
    controller: App\Controller\AddCastleController:addFinishCastleAction